---
- name: Install PostgreSQL
  yum:
    name: {{ item }}
    state: present
    loop:
      - python-psycopg2
      - postgresql-server
      - postgresql


- name: Get Database Exist Status
  stat:
    path: "{{ postgres_data_dir }}/PG_VERSION"
  register: pgdata


- name: Ensure that PostgreSQL Database Is Initialized
  command: "sudo -u postgres bash -c 'initdb -D {{ postgres_data_dir }}'"
  when: not pgdata.stat.exists


- name: Configure PostgreSQL
  template:
    src: {{ item.0 }}
    dest: "{{ postgres_data_dir }}/{{ item.1 }}"
    owner: postgres
    group: postgres
    mode: 644
  loop:
      - [ 'var/lib/pgsql/data/postgresql.conf.j2', 'postgresql.conf' ]
      - [ 'var/lib/pgsql/data/pg_hba.conf.j2', 'pg_hba.conf' ]


- name: Install python-pip
  yum:
    name: python-pip
    state: present


- name: Ensure that PostgreSQL Service Is Running
  service: 
    name: postgresql
    state: started
    enabled: yes