#! /usr/bin/env ansible-playbook
---
- name: Install nginx
  hosts: webservers
  become: true
  roles:
    - nginx


- name: Install PostgreSQL
  hosts: webservers
  become: true
  roles:
    - postgresql-install


- name: Fill PostgreSQL with Data
  hosts: webservers
  become: true
  roles:
    - postgresql-fill
